version: "3.9"

x-service:
  &service
  build:
    context: .
  volumes:
    # bind mount a directory to share the output of the formatter and test runner
    - type: bind
      source: .
      target: /code

services:
  format:
    command: black tests/
    <<: *service
  tests:
    command: pytest --report-log pytest.json
    <<: *service
    depends_on:
      - format
