version: "3.9"

x-service:
  &service
  build:
    context: .
  volumes:
    # bind mount a directory to share the output of the formatter and test runner
    - type: bind
      source: .
      target: /code

services:
  format:
    command: black tests/
    <<: *service
  tests:
    command: pytest --report-log $ENGI_WORKING_DIR/pytest.json
    <<: *service
    depends_on:
      - format
    mem_limit: 4g
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
