version: "3.9"

services:
  format:
    build: .
    command: black tests/
  tests:
    build: .
    command: pytest --report-log $ENGI_WORKING_DIR/pytest.json
    depends_on:
      - format
    mem_limit: 1g
    cpus: 2
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
