version: "3.9"

services:
  format:
    build: .
    command: black tests/
  solhint:
    build: .
    command: black tests/
  tests:
    build: .
    platform: linux/x86_64
    command: pytest --suppress-tests-failed-exit-code --report-log $ENGI_WORKING_DIR/pytest.json
    depends_on:
      - format
      - solhint
    mem_limit: 10g
    cpus: 2
    volumes:
      - type: volume
        source: output
        target: $ENGI_WORKING_DIR
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
